#ifndef __CONST_MENU_UP__
#define __CONST_MENU_UP__

#define EKRAN_SETPOINT_UP_GROUP1   (EKRAN_SETPOINT_UMAX_GROUP4 + 1)
#define EKRAN_SETPOINT_UP_GROUP2   (EKRAN_SETPOINT_UP_GROUP1 + 1)
#define EKRAN_SETPOINT_UP_GROUP3   (EKRAN_SETPOINT_UP_GROUP2 + 1)
#define EKRAN_SETPOINT_UP_GROUP4   (EKRAN_SETPOINT_UP_GROUP3 + 1)
#define EKRAN_TIMEOUT_UP_GROUP1    (EKRAN_TIMEOUT_UMAX_GROUP4 + 1)
#define EKRAN_TIMEOUT_UP_GROUP2    (EKRAN_TIMEOUT_UP_GROUP1  + 1)
#define EKRAN_TIMEOUT_UP_GROUP3    (EKRAN_TIMEOUT_UP_GROUP2  + 1)
#define EKRAN_TIMEOUT_UP_GROUP4    (EKRAN_TIMEOUT_UP_GROUP3  + 1)
#define EKRAN_CONTROL_UP           (EKRAN_CONTROL_UMAX  + 1)

#endif
