#ifndef DIAGNOSTYKA_MO
#define DIAGNOSTYKA_MO

enum __diagnostyka_mo
{
  ERROR_RECEIVING_CANAL_1,
  ERROR_RECEIVED_PACKET_CANAL_1,
  ERROR_REQUEST_CANAL_1,
  ERROR_NO_ANSWER_CANAL_1,

  ERROR_RECEIVING_CANAL_2,
  ERROR_RECEIVED_PACKET_CANAL_2,
  ERROR_REQUEST_CANAL_2,
};

#endif
